Package node engine version defined
Defined the node engine version so that if you're using glitch no 'TypeError: fields.flat is not a function' exceptions occur when you're tryna host